/*
Tyk Gateway API

The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.  **Warning: Under no circumstances should outside parties be granted access to this API.**  The Tyk Gateway API is capable of:  * Managing session objects (key generation) * Managing and listing policies * Managing and listing API Definitions (only when not using the Dashboard) * Hot reloads / reloading a cluster configuration * OAuth client creation (only when not using the Dashboard)   In order to use the Gateway API, you'll need to set the `secret` parameter in your tyk.conf file.  The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:  ``` x-tyk-authorization: <your-secret> ``` <br/> <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>

API version: 3.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// APIDefinitionUptimeTests struct for APIDefinitionUptimeTests
type APIDefinitionUptimeTests struct {
	CheckList []HostCheckObject `json:"check_list,omitempty"`
	Config *APIDefinitionUptimeTestsConfig `json:"config,omitempty"`
}

// NewAPIDefinitionUptimeTests instantiates a new APIDefinitionUptimeTests object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPIDefinitionUptimeTests() *APIDefinitionUptimeTests {
	this := APIDefinitionUptimeTests{}
	return &this
}

// NewAPIDefinitionUptimeTestsWithDefaults instantiates a new APIDefinitionUptimeTests object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPIDefinitionUptimeTestsWithDefaults() *APIDefinitionUptimeTests {
	this := APIDefinitionUptimeTests{}
	return &this
}

// GetCheckList returns the CheckList field value if set, zero value otherwise.
func (o *APIDefinitionUptimeTests) GetCheckList() []HostCheckObject {
	if o == nil || o.CheckList == nil {
		var ret []HostCheckObject
		return ret
	}
	return o.CheckList
}

// GetCheckListOk returns a tuple with the CheckList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionUptimeTests) GetCheckListOk() ([]HostCheckObject, bool) {
	if o == nil || o.CheckList == nil {
		return nil, false
	}
	return o.CheckList, true
}

// HasCheckList returns a boolean if a field has been set.
func (o *APIDefinitionUptimeTests) HasCheckList() bool {
	if o != nil && o.CheckList != nil {
		return true
	}

	return false
}

// SetCheckList gets a reference to the given []HostCheckObject and assigns it to the CheckList field.
func (o *APIDefinitionUptimeTests) SetCheckList(v []HostCheckObject) {
	o.CheckList = v
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *APIDefinitionUptimeTests) GetConfig() APIDefinitionUptimeTestsConfig {
	if o == nil || o.Config == nil {
		var ret APIDefinitionUptimeTestsConfig
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionUptimeTests) GetConfigOk() (*APIDefinitionUptimeTestsConfig, bool) {
	if o == nil || o.Config == nil {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *APIDefinitionUptimeTests) HasConfig() bool {
	if o != nil && o.Config != nil {
		return true
	}

	return false
}

// SetConfig gets a reference to the given APIDefinitionUptimeTestsConfig and assigns it to the Config field.
func (o *APIDefinitionUptimeTests) SetConfig(v APIDefinitionUptimeTestsConfig) {
	o.Config = &v
}

func (o APIDefinitionUptimeTests) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CheckList != nil {
		toSerialize["check_list"] = o.CheckList
	}
	if o.Config != nil {
		toSerialize["config"] = o.Config
	}
	return json.Marshal(toSerialize)
}

type NullableAPIDefinitionUptimeTests struct {
	value *APIDefinitionUptimeTests
	isSet bool
}

func (v NullableAPIDefinitionUptimeTests) Get() *APIDefinitionUptimeTests {
	return v.value
}

func (v *NullableAPIDefinitionUptimeTests) Set(val *APIDefinitionUptimeTests) {
	v.value = val
	v.isSet = true
}

func (v NullableAPIDefinitionUptimeTests) IsSet() bool {
	return v.isSet
}

func (v *NullableAPIDefinitionUptimeTests) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPIDefinitionUptimeTests(val *APIDefinitionUptimeTests) *NullableAPIDefinitionUptimeTests {
	return &NullableAPIDefinitionUptimeTests{value: val, isSet: true}
}

func (v NullableAPIDefinitionUptimeTests) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPIDefinitionUptimeTests) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


