/*
Tyk Gateway API

The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.  **Warning: Under no circumstances should outside parties be granted access to this API.**  The Tyk Gateway API is capable of:  * Managing session objects (key generation) * Managing and listing policies * Managing and listing API Definitions (only when not using the Dashboard) * Hot reloads / reloading a cluster configuration * OAuth client creation (only when not using the Dashboard)   In order to use the Gateway API, you'll need to set the `secret` parameter in your tyk.conf file.  The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:  ``` x-tyk-authorization: <your-secret> ``` <br/> <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>

API version: 3.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// OASSchemaResponse OAS schema endpoint response
type OASSchemaResponse struct {
	Status *string `json:"status,omitempty"`
	Message *string `json:"message,omitempty"`
	// <OAS schema definition>
	Schema *string `json:"schema,omitempty"`
}

// NewOASSchemaResponse instantiates a new OASSchemaResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOASSchemaResponse() *OASSchemaResponse {
	this := OASSchemaResponse{}
	return &this
}

// NewOASSchemaResponseWithDefaults instantiates a new OASSchemaResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOASSchemaResponseWithDefaults() *OASSchemaResponse {
	this := OASSchemaResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *OASSchemaResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OASSchemaResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *OASSchemaResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *OASSchemaResponse) SetStatus(v string) {
	o.Status = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *OASSchemaResponse) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OASSchemaResponse) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *OASSchemaResponse) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *OASSchemaResponse) SetMessage(v string) {
	o.Message = &v
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *OASSchemaResponse) GetSchema() string {
	if o == nil || o.Schema == nil {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OASSchemaResponse) GetSchemaOk() (*string, bool) {
	if o == nil || o.Schema == nil {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *OASSchemaResponse) HasSchema() bool {
	if o != nil && o.Schema != nil {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *OASSchemaResponse) SetSchema(v string) {
	o.Schema = &v
}

func (o OASSchemaResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	if o.Schema != nil {
		toSerialize["schema"] = o.Schema
	}
	return json.Marshal(toSerialize)
}

type NullableOASSchemaResponse struct {
	value *OASSchemaResponse
	isSet bool
}

func (v NullableOASSchemaResponse) Get() *OASSchemaResponse {
	return v.value
}

func (v *NullableOASSchemaResponse) Set(val *OASSchemaResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOASSchemaResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOASSchemaResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOASSchemaResponse(val *OASSchemaResponse) *NullableOASSchemaResponse {
	return &NullableOASSchemaResponse{value: val, isSet: true}
}

func (v NullableOASSchemaResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOASSchemaResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


