/*
Tyk Gateway API

The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.  **Warning: Under no circumstances should outside parties be granted access to this API.**  The Tyk Gateway API is capable of:  * Managing session objects (key generation) * Managing and listing policies * Managing and listing API Definitions (only when not using the Dashboard) * Hot reloads / reloading a cluster configuration * OAuth client creation (only when not using the Dashboard)   In order to use the Gateway API, you'll need to set the `secret` parameter in your tyk.conf file.  The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:  ``` x-tyk-authorization: <your-secret> ``` <br/> <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>

API version: 3.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// URLRewriteMeta struct for URLRewriteMeta
type URLRewriteMeta struct {
	MatchRegexp *Regexp `json:"MatchRegexp,omitempty"`
	MatchPattern *string `json:"match_pattern,omitempty"`
	Method *string `json:"method,omitempty"`
	Path *string `json:"path,omitempty"`
	RewriteTo *string `json:"rewrite_to,omitempty"`
	Triggers []RoutingTrigger `json:"triggers,omitempty"`
}

// NewURLRewriteMeta instantiates a new URLRewriteMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewURLRewriteMeta() *URLRewriteMeta {
	this := URLRewriteMeta{}
	return &this
}

// NewURLRewriteMetaWithDefaults instantiates a new URLRewriteMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewURLRewriteMetaWithDefaults() *URLRewriteMeta {
	this := URLRewriteMeta{}
	return &this
}

// GetMatchRegexp returns the MatchRegexp field value if set, zero value otherwise.
func (o *URLRewriteMeta) GetMatchRegexp() Regexp {
	if o == nil || o.MatchRegexp == nil {
		var ret Regexp
		return ret
	}
	return *o.MatchRegexp
}

// GetMatchRegexpOk returns a tuple with the MatchRegexp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *URLRewriteMeta) GetMatchRegexpOk() (*Regexp, bool) {
	if o == nil || o.MatchRegexp == nil {
		return nil, false
	}
	return o.MatchRegexp, true
}

// HasMatchRegexp returns a boolean if a field has been set.
func (o *URLRewriteMeta) HasMatchRegexp() bool {
	if o != nil && o.MatchRegexp != nil {
		return true
	}

	return false
}

// SetMatchRegexp gets a reference to the given Regexp and assigns it to the MatchRegexp field.
func (o *URLRewriteMeta) SetMatchRegexp(v Regexp) {
	o.MatchRegexp = &v
}

// GetMatchPattern returns the MatchPattern field value if set, zero value otherwise.
func (o *URLRewriteMeta) GetMatchPattern() string {
	if o == nil || o.MatchPattern == nil {
		var ret string
		return ret
	}
	return *o.MatchPattern
}

// GetMatchPatternOk returns a tuple with the MatchPattern field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *URLRewriteMeta) GetMatchPatternOk() (*string, bool) {
	if o == nil || o.MatchPattern == nil {
		return nil, false
	}
	return o.MatchPattern, true
}

// HasMatchPattern returns a boolean if a field has been set.
func (o *URLRewriteMeta) HasMatchPattern() bool {
	if o != nil && o.MatchPattern != nil {
		return true
	}

	return false
}

// SetMatchPattern gets a reference to the given string and assigns it to the MatchPattern field.
func (o *URLRewriteMeta) SetMatchPattern(v string) {
	o.MatchPattern = &v
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *URLRewriteMeta) GetMethod() string {
	if o == nil || o.Method == nil {
		var ret string
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *URLRewriteMeta) GetMethodOk() (*string, bool) {
	if o == nil || o.Method == nil {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *URLRewriteMeta) HasMethod() bool {
	if o != nil && o.Method != nil {
		return true
	}

	return false
}

// SetMethod gets a reference to the given string and assigns it to the Method field.
func (o *URLRewriteMeta) SetMethod(v string) {
	o.Method = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *URLRewriteMeta) GetPath() string {
	if o == nil || o.Path == nil {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *URLRewriteMeta) GetPathOk() (*string, bool) {
	if o == nil || o.Path == nil {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *URLRewriteMeta) HasPath() bool {
	if o != nil && o.Path != nil {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *URLRewriteMeta) SetPath(v string) {
	o.Path = &v
}

// GetRewriteTo returns the RewriteTo field value if set, zero value otherwise.
func (o *URLRewriteMeta) GetRewriteTo() string {
	if o == nil || o.RewriteTo == nil {
		var ret string
		return ret
	}
	return *o.RewriteTo
}

// GetRewriteToOk returns a tuple with the RewriteTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *URLRewriteMeta) GetRewriteToOk() (*string, bool) {
	if o == nil || o.RewriteTo == nil {
		return nil, false
	}
	return o.RewriteTo, true
}

// HasRewriteTo returns a boolean if a field has been set.
func (o *URLRewriteMeta) HasRewriteTo() bool {
	if o != nil && o.RewriteTo != nil {
		return true
	}

	return false
}

// SetRewriteTo gets a reference to the given string and assigns it to the RewriteTo field.
func (o *URLRewriteMeta) SetRewriteTo(v string) {
	o.RewriteTo = &v
}

// GetTriggers returns the Triggers field value if set, zero value otherwise.
func (o *URLRewriteMeta) GetTriggers() []RoutingTrigger {
	if o == nil || o.Triggers == nil {
		var ret []RoutingTrigger
		return ret
	}
	return o.Triggers
}

// GetTriggersOk returns a tuple with the Triggers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *URLRewriteMeta) GetTriggersOk() ([]RoutingTrigger, bool) {
	if o == nil || o.Triggers == nil {
		return nil, false
	}
	return o.Triggers, true
}

// HasTriggers returns a boolean if a field has been set.
func (o *URLRewriteMeta) HasTriggers() bool {
	if o != nil && o.Triggers != nil {
		return true
	}

	return false
}

// SetTriggers gets a reference to the given []RoutingTrigger and assigns it to the Triggers field.
func (o *URLRewriteMeta) SetTriggers(v []RoutingTrigger) {
	o.Triggers = v
}

func (o URLRewriteMeta) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.MatchRegexp != nil {
		toSerialize["MatchRegexp"] = o.MatchRegexp
	}
	if o.MatchPattern != nil {
		toSerialize["match_pattern"] = o.MatchPattern
	}
	if o.Method != nil {
		toSerialize["method"] = o.Method
	}
	if o.Path != nil {
		toSerialize["path"] = o.Path
	}
	if o.RewriteTo != nil {
		toSerialize["rewrite_to"] = o.RewriteTo
	}
	if o.Triggers != nil {
		toSerialize["triggers"] = o.Triggers
	}
	return json.Marshal(toSerialize)
}

type NullableURLRewriteMeta struct {
	value *URLRewriteMeta
	isSet bool
}

func (v NullableURLRewriteMeta) Get() *URLRewriteMeta {
	return v.value
}

func (v *NullableURLRewriteMeta) Set(val *URLRewriteMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableURLRewriteMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableURLRewriteMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableURLRewriteMeta(val *URLRewriteMeta) *NullableURLRewriteMeta {
	return &NullableURLRewriteMeta{value: val, isSet: true}
}

func (v NullableURLRewriteMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableURLRewriteMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


