/*
Tyk Gateway API

The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.  **Warning: Under no circumstances should outside parties be granted access to this API.**  The Tyk Gateway API is capable of:  * Managing session objects (key generation) * Managing and listing policies * Managing and listing API Definitions (only when not using the Dashboard) * Hot reloads / reloading a cluster configuration * OAuth client creation (only when not using the Dashboard)   In order to use the Gateway API, you'll need to set the `secret` parameter in your tyk.conf file.  The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:  ``` x-tyk-authorization: <your-secret> ``` <br/> <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>

API version: 3.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// APIDefinitionVersionData struct for APIDefinitionVersionData
type APIDefinitionVersionData struct {
	DefaultVersion *string `json:"default_version,omitempty"`
	NotVersioned *bool `json:"not_versioned,omitempty"`
	Versions *map[string]VersionInfo `json:"versions,omitempty"`
}

// NewAPIDefinitionVersionData instantiates a new APIDefinitionVersionData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPIDefinitionVersionData() *APIDefinitionVersionData {
	this := APIDefinitionVersionData{}
	return &this
}

// NewAPIDefinitionVersionDataWithDefaults instantiates a new APIDefinitionVersionData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPIDefinitionVersionDataWithDefaults() *APIDefinitionVersionData {
	this := APIDefinitionVersionData{}
	return &this
}

// GetDefaultVersion returns the DefaultVersion field value if set, zero value otherwise.
func (o *APIDefinitionVersionData) GetDefaultVersion() string {
	if o == nil || o.DefaultVersion == nil {
		var ret string
		return ret
	}
	return *o.DefaultVersion
}

// GetDefaultVersionOk returns a tuple with the DefaultVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionVersionData) GetDefaultVersionOk() (*string, bool) {
	if o == nil || o.DefaultVersion == nil {
		return nil, false
	}
	return o.DefaultVersion, true
}

// HasDefaultVersion returns a boolean if a field has been set.
func (o *APIDefinitionVersionData) HasDefaultVersion() bool {
	if o != nil && o.DefaultVersion != nil {
		return true
	}

	return false
}

// SetDefaultVersion gets a reference to the given string and assigns it to the DefaultVersion field.
func (o *APIDefinitionVersionData) SetDefaultVersion(v string) {
	o.DefaultVersion = &v
}

// GetNotVersioned returns the NotVersioned field value if set, zero value otherwise.
func (o *APIDefinitionVersionData) GetNotVersioned() bool {
	if o == nil || o.NotVersioned == nil {
		var ret bool
		return ret
	}
	return *o.NotVersioned
}

// GetNotVersionedOk returns a tuple with the NotVersioned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionVersionData) GetNotVersionedOk() (*bool, bool) {
	if o == nil || o.NotVersioned == nil {
		return nil, false
	}
	return o.NotVersioned, true
}

// HasNotVersioned returns a boolean if a field has been set.
func (o *APIDefinitionVersionData) HasNotVersioned() bool {
	if o != nil && o.NotVersioned != nil {
		return true
	}

	return false
}

// SetNotVersioned gets a reference to the given bool and assigns it to the NotVersioned field.
func (o *APIDefinitionVersionData) SetNotVersioned(v bool) {
	o.NotVersioned = &v
}

// GetVersions returns the Versions field value if set, zero value otherwise.
func (o *APIDefinitionVersionData) GetVersions() map[string]VersionInfo {
	if o == nil || o.Versions == nil {
		var ret map[string]VersionInfo
		return ret
	}
	return *o.Versions
}

// GetVersionsOk returns a tuple with the Versions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionVersionData) GetVersionsOk() (*map[string]VersionInfo, bool) {
	if o == nil || o.Versions == nil {
		return nil, false
	}
	return o.Versions, true
}

// HasVersions returns a boolean if a field has been set.
func (o *APIDefinitionVersionData) HasVersions() bool {
	if o != nil && o.Versions != nil {
		return true
	}

	return false
}

// SetVersions gets a reference to the given map[string]VersionInfo and assigns it to the Versions field.
func (o *APIDefinitionVersionData) SetVersions(v map[string]VersionInfo) {
	o.Versions = &v
}

func (o APIDefinitionVersionData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DefaultVersion != nil {
		toSerialize["default_version"] = o.DefaultVersion
	}
	if o.NotVersioned != nil {
		toSerialize["not_versioned"] = o.NotVersioned
	}
	if o.Versions != nil {
		toSerialize["versions"] = o.Versions
	}
	return json.Marshal(toSerialize)
}

type NullableAPIDefinitionVersionData struct {
	value *APIDefinitionVersionData
	isSet bool
}

func (v NullableAPIDefinitionVersionData) Get() *APIDefinitionVersionData {
	return v.value
}

func (v *NullableAPIDefinitionVersionData) Set(val *APIDefinitionVersionData) {
	v.value = val
	v.isSet = true
}

func (v NullableAPIDefinitionVersionData) IsSet() bool {
	return v.isSet
}

func (v *NullableAPIDefinitionVersionData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPIDefinitionVersionData(val *APIDefinitionVersionData) *NullableAPIDefinitionVersionData {
	return &NullableAPIDefinitionVersionData{value: val, isSet: true}
}

func (v NullableAPIDefinitionVersionData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPIDefinitionVersionData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


