/*
Tyk Gateway API

The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.  **Warning: Under no circumstances should outside parties be granted access to this API.**  The Tyk Gateway API is capable of:  * Managing session objects (key generation) * Managing and listing policies * Managing and listing API Definitions (only when not using the Dashboard) * Hot reloads / reloading a cluster configuration * OAuth client creation (only when not using the Dashboard)   In order to use the Gateway API, you'll need to set the `secret` parameter in your tyk.conf file.  The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:  ``` x-tyk-authorization: <your-secret> ``` <br/> <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>

API version: 3.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// APIDefinitionProxyTransport struct for APIDefinitionProxyTransport
type APIDefinitionProxyTransport struct {
	ProxyUrl *string `json:"proxy_url,omitempty"`
	SslCiphers []string `json:"ssl_ciphers,omitempty"`
	SslInsecureSkipVerify *bool `json:"ssl_insecure_skip_verify,omitempty"`
	SslMinVersion *int32 `json:"ssl_min_version,omitempty"`
}

// NewAPIDefinitionProxyTransport instantiates a new APIDefinitionProxyTransport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPIDefinitionProxyTransport() *APIDefinitionProxyTransport {
	this := APIDefinitionProxyTransport{}
	return &this
}

// NewAPIDefinitionProxyTransportWithDefaults instantiates a new APIDefinitionProxyTransport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPIDefinitionProxyTransportWithDefaults() *APIDefinitionProxyTransport {
	this := APIDefinitionProxyTransport{}
	return &this
}

// GetProxyUrl returns the ProxyUrl field value if set, zero value otherwise.
func (o *APIDefinitionProxyTransport) GetProxyUrl() string {
	if o == nil || o.ProxyUrl == nil {
		var ret string
		return ret
	}
	return *o.ProxyUrl
}

// GetProxyUrlOk returns a tuple with the ProxyUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionProxyTransport) GetProxyUrlOk() (*string, bool) {
	if o == nil || o.ProxyUrl == nil {
		return nil, false
	}
	return o.ProxyUrl, true
}

// HasProxyUrl returns a boolean if a field has been set.
func (o *APIDefinitionProxyTransport) HasProxyUrl() bool {
	if o != nil && o.ProxyUrl != nil {
		return true
	}

	return false
}

// SetProxyUrl gets a reference to the given string and assigns it to the ProxyUrl field.
func (o *APIDefinitionProxyTransport) SetProxyUrl(v string) {
	o.ProxyUrl = &v
}

// GetSslCiphers returns the SslCiphers field value if set, zero value otherwise.
func (o *APIDefinitionProxyTransport) GetSslCiphers() []string {
	if o == nil || o.SslCiphers == nil {
		var ret []string
		return ret
	}
	return o.SslCiphers
}

// GetSslCiphersOk returns a tuple with the SslCiphers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionProxyTransport) GetSslCiphersOk() ([]string, bool) {
	if o == nil || o.SslCiphers == nil {
		return nil, false
	}
	return o.SslCiphers, true
}

// HasSslCiphers returns a boolean if a field has been set.
func (o *APIDefinitionProxyTransport) HasSslCiphers() bool {
	if o != nil && o.SslCiphers != nil {
		return true
	}

	return false
}

// SetSslCiphers gets a reference to the given []string and assigns it to the SslCiphers field.
func (o *APIDefinitionProxyTransport) SetSslCiphers(v []string) {
	o.SslCiphers = v
}

// GetSslInsecureSkipVerify returns the SslInsecureSkipVerify field value if set, zero value otherwise.
func (o *APIDefinitionProxyTransport) GetSslInsecureSkipVerify() bool {
	if o == nil || o.SslInsecureSkipVerify == nil {
		var ret bool
		return ret
	}
	return *o.SslInsecureSkipVerify
}

// GetSslInsecureSkipVerifyOk returns a tuple with the SslInsecureSkipVerify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionProxyTransport) GetSslInsecureSkipVerifyOk() (*bool, bool) {
	if o == nil || o.SslInsecureSkipVerify == nil {
		return nil, false
	}
	return o.SslInsecureSkipVerify, true
}

// HasSslInsecureSkipVerify returns a boolean if a field has been set.
func (o *APIDefinitionProxyTransport) HasSslInsecureSkipVerify() bool {
	if o != nil && o.SslInsecureSkipVerify != nil {
		return true
	}

	return false
}

// SetSslInsecureSkipVerify gets a reference to the given bool and assigns it to the SslInsecureSkipVerify field.
func (o *APIDefinitionProxyTransport) SetSslInsecureSkipVerify(v bool) {
	o.SslInsecureSkipVerify = &v
}

// GetSslMinVersion returns the SslMinVersion field value if set, zero value otherwise.
func (o *APIDefinitionProxyTransport) GetSslMinVersion() int32 {
	if o == nil || o.SslMinVersion == nil {
		var ret int32
		return ret
	}
	return *o.SslMinVersion
}

// GetSslMinVersionOk returns a tuple with the SslMinVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionProxyTransport) GetSslMinVersionOk() (*int32, bool) {
	if o == nil || o.SslMinVersion == nil {
		return nil, false
	}
	return o.SslMinVersion, true
}

// HasSslMinVersion returns a boolean if a field has been set.
func (o *APIDefinitionProxyTransport) HasSslMinVersion() bool {
	if o != nil && o.SslMinVersion != nil {
		return true
	}

	return false
}

// SetSslMinVersion gets a reference to the given int32 and assigns it to the SslMinVersion field.
func (o *APIDefinitionProxyTransport) SetSslMinVersion(v int32) {
	o.SslMinVersion = &v
}

func (o APIDefinitionProxyTransport) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ProxyUrl != nil {
		toSerialize["proxy_url"] = o.ProxyUrl
	}
	if o.SslCiphers != nil {
		toSerialize["ssl_ciphers"] = o.SslCiphers
	}
	if o.SslInsecureSkipVerify != nil {
		toSerialize["ssl_insecure_skip_verify"] = o.SslInsecureSkipVerify
	}
	if o.SslMinVersion != nil {
		toSerialize["ssl_min_version"] = o.SslMinVersion
	}
	return json.Marshal(toSerialize)
}

type NullableAPIDefinitionProxyTransport struct {
	value *APIDefinitionProxyTransport
	isSet bool
}

func (v NullableAPIDefinitionProxyTransport) Get() *APIDefinitionProxyTransport {
	return v.value
}

func (v *NullableAPIDefinitionProxyTransport) Set(val *APIDefinitionProxyTransport) {
	v.value = val
	v.isSet = true
}

func (v NullableAPIDefinitionProxyTransport) IsSet() bool {
	return v.isSet
}

func (v *NullableAPIDefinitionProxyTransport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPIDefinitionProxyTransport(val *APIDefinitionProxyTransport) *NullableAPIDefinitionProxyTransport {
	return &NullableAPIDefinitionProxyTransport{value: val, isSet: true}
}

func (v NullableAPIDefinitionProxyTransport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPIDefinitionProxyTransport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


