/*
Tyk Gateway API

The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.  **Warning: Under no circumstances should outside parties be granted access to this API.**  The Tyk Gateway API is capable of:  * Managing session objects (key generation) * Managing and listing policies * Managing and listing API Definitions (only when not using the Dashboard) * Hot reloads / reloading a cluster configuration * OAuth client creation (only when not using the Dashboard)   In order to use the Gateway API, you'll need to set the `secret` parameter in your tyk.conf file.  The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:  ``` x-tyk-authorization: <your-secret> ``` <br/> <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>

API version: 3.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// HeaderInjectionMeta struct for HeaderInjectionMeta
type HeaderInjectionMeta struct {
	ActOn *bool `json:"act_on,omitempty"`
	AddHeaders *map[string]string `json:"add_headers,omitempty"`
	DeleteHeaders []string `json:"delete_headers,omitempty"`
	Method *string `json:"method,omitempty"`
	Path *string `json:"path,omitempty"`
}

// NewHeaderInjectionMeta instantiates a new HeaderInjectionMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHeaderInjectionMeta() *HeaderInjectionMeta {
	this := HeaderInjectionMeta{}
	return &this
}

// NewHeaderInjectionMetaWithDefaults instantiates a new HeaderInjectionMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHeaderInjectionMetaWithDefaults() *HeaderInjectionMeta {
	this := HeaderInjectionMeta{}
	return &this
}

// GetActOn returns the ActOn field value if set, zero value otherwise.
func (o *HeaderInjectionMeta) GetActOn() bool {
	if o == nil || o.ActOn == nil {
		var ret bool
		return ret
	}
	return *o.ActOn
}

// GetActOnOk returns a tuple with the ActOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HeaderInjectionMeta) GetActOnOk() (*bool, bool) {
	if o == nil || o.ActOn == nil {
		return nil, false
	}
	return o.ActOn, true
}

// HasActOn returns a boolean if a field has been set.
func (o *HeaderInjectionMeta) HasActOn() bool {
	if o != nil && o.ActOn != nil {
		return true
	}

	return false
}

// SetActOn gets a reference to the given bool and assigns it to the ActOn field.
func (o *HeaderInjectionMeta) SetActOn(v bool) {
	o.ActOn = &v
}

// GetAddHeaders returns the AddHeaders field value if set, zero value otherwise.
func (o *HeaderInjectionMeta) GetAddHeaders() map[string]string {
	if o == nil || o.AddHeaders == nil {
		var ret map[string]string
		return ret
	}
	return *o.AddHeaders
}

// GetAddHeadersOk returns a tuple with the AddHeaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HeaderInjectionMeta) GetAddHeadersOk() (*map[string]string, bool) {
	if o == nil || o.AddHeaders == nil {
		return nil, false
	}
	return o.AddHeaders, true
}

// HasAddHeaders returns a boolean if a field has been set.
func (o *HeaderInjectionMeta) HasAddHeaders() bool {
	if o != nil && o.AddHeaders != nil {
		return true
	}

	return false
}

// SetAddHeaders gets a reference to the given map[string]string and assigns it to the AddHeaders field.
func (o *HeaderInjectionMeta) SetAddHeaders(v map[string]string) {
	o.AddHeaders = &v
}

// GetDeleteHeaders returns the DeleteHeaders field value if set, zero value otherwise.
func (o *HeaderInjectionMeta) GetDeleteHeaders() []string {
	if o == nil || o.DeleteHeaders == nil {
		var ret []string
		return ret
	}
	return o.DeleteHeaders
}

// GetDeleteHeadersOk returns a tuple with the DeleteHeaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HeaderInjectionMeta) GetDeleteHeadersOk() ([]string, bool) {
	if o == nil || o.DeleteHeaders == nil {
		return nil, false
	}
	return o.DeleteHeaders, true
}

// HasDeleteHeaders returns a boolean if a field has been set.
func (o *HeaderInjectionMeta) HasDeleteHeaders() bool {
	if o != nil && o.DeleteHeaders != nil {
		return true
	}

	return false
}

// SetDeleteHeaders gets a reference to the given []string and assigns it to the DeleteHeaders field.
func (o *HeaderInjectionMeta) SetDeleteHeaders(v []string) {
	o.DeleteHeaders = v
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *HeaderInjectionMeta) GetMethod() string {
	if o == nil || o.Method == nil {
		var ret string
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HeaderInjectionMeta) GetMethodOk() (*string, bool) {
	if o == nil || o.Method == nil {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *HeaderInjectionMeta) HasMethod() bool {
	if o != nil && o.Method != nil {
		return true
	}

	return false
}

// SetMethod gets a reference to the given string and assigns it to the Method field.
func (o *HeaderInjectionMeta) SetMethod(v string) {
	o.Method = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *HeaderInjectionMeta) GetPath() string {
	if o == nil || o.Path == nil {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HeaderInjectionMeta) GetPathOk() (*string, bool) {
	if o == nil || o.Path == nil {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *HeaderInjectionMeta) HasPath() bool {
	if o != nil && o.Path != nil {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *HeaderInjectionMeta) SetPath(v string) {
	o.Path = &v
}

func (o HeaderInjectionMeta) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ActOn != nil {
		toSerialize["act_on"] = o.ActOn
	}
	if o.AddHeaders != nil {
		toSerialize["add_headers"] = o.AddHeaders
	}
	if o.DeleteHeaders != nil {
		toSerialize["delete_headers"] = o.DeleteHeaders
	}
	if o.Method != nil {
		toSerialize["method"] = o.Method
	}
	if o.Path != nil {
		toSerialize["path"] = o.Path
	}
	return json.Marshal(toSerialize)
}

type NullableHeaderInjectionMeta struct {
	value *HeaderInjectionMeta
	isSet bool
}

func (v NullableHeaderInjectionMeta) Get() *HeaderInjectionMeta {
	return v.value
}

func (v *NullableHeaderInjectionMeta) Set(val *HeaderInjectionMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableHeaderInjectionMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableHeaderInjectionMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHeaderInjectionMeta(val *HeaderInjectionMeta) *NullableHeaderInjectionMeta {
	return &NullableHeaderInjectionMeta{value: val, isSet: true}
}

func (v NullableHeaderInjectionMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHeaderInjectionMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


