/*
Tyk Gateway API

The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.  **Warning: Under no circumstances should outside parties be granted access to this API.**  The Tyk Gateway API is capable of:  * Managing session objects (key generation) * Managing and listing policies * Managing and listing API Definitions (only when not using the Dashboard) * Hot reloads / reloading a cluster configuration * OAuth client creation (only when not using the Dashboard)   In order to use the Gateway API, you'll need to set the `secret` parameter in your tyk.conf file.  The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:  ``` x-tyk-authorization: <your-secret> ``` <br/> <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>

API version: 3.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// MiddlewareDefinition struct for MiddlewareDefinition
type MiddlewareDefinition struct {
	Name *string `json:"name,omitempty"`
	Path *string `json:"path,omitempty"`
	RequireSession *bool `json:"require_session,omitempty"`
}

// NewMiddlewareDefinition instantiates a new MiddlewareDefinition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMiddlewareDefinition() *MiddlewareDefinition {
	this := MiddlewareDefinition{}
	return &this
}

// NewMiddlewareDefinitionWithDefaults instantiates a new MiddlewareDefinition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMiddlewareDefinitionWithDefaults() *MiddlewareDefinition {
	this := MiddlewareDefinition{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MiddlewareDefinition) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MiddlewareDefinition) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MiddlewareDefinition) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MiddlewareDefinition) SetName(v string) {
	o.Name = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *MiddlewareDefinition) GetPath() string {
	if o == nil || o.Path == nil {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MiddlewareDefinition) GetPathOk() (*string, bool) {
	if o == nil || o.Path == nil {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *MiddlewareDefinition) HasPath() bool {
	if o != nil && o.Path != nil {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *MiddlewareDefinition) SetPath(v string) {
	o.Path = &v
}

// GetRequireSession returns the RequireSession field value if set, zero value otherwise.
func (o *MiddlewareDefinition) GetRequireSession() bool {
	if o == nil || o.RequireSession == nil {
		var ret bool
		return ret
	}
	return *o.RequireSession
}

// GetRequireSessionOk returns a tuple with the RequireSession field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MiddlewareDefinition) GetRequireSessionOk() (*bool, bool) {
	if o == nil || o.RequireSession == nil {
		return nil, false
	}
	return o.RequireSession, true
}

// HasRequireSession returns a boolean if a field has been set.
func (o *MiddlewareDefinition) HasRequireSession() bool {
	if o != nil && o.RequireSession != nil {
		return true
	}

	return false
}

// SetRequireSession gets a reference to the given bool and assigns it to the RequireSession field.
func (o *MiddlewareDefinition) SetRequireSession(v bool) {
	o.RequireSession = &v
}

func (o MiddlewareDefinition) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Path != nil {
		toSerialize["path"] = o.Path
	}
	if o.RequireSession != nil {
		toSerialize["require_session"] = o.RequireSession
	}
	return json.Marshal(toSerialize)
}

type NullableMiddlewareDefinition struct {
	value *MiddlewareDefinition
	isSet bool
}

func (v NullableMiddlewareDefinition) Get() *MiddlewareDefinition {
	return v.value
}

func (v *NullableMiddlewareDefinition) Set(val *MiddlewareDefinition) {
	v.value = val
	v.isSet = true
}

func (v NullableMiddlewareDefinition) IsSet() bool {
	return v.isSet
}

func (v *NullableMiddlewareDefinition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMiddlewareDefinition(val *MiddlewareDefinition) *NullableMiddlewareDefinition {
	return &NullableMiddlewareDefinition{value: val, isSet: true}
}

func (v NullableMiddlewareDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMiddlewareDefinition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


