/*
Tyk Gateway API

The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.  **Warning: Under no circumstances should outside parties be granted access to this API.**  The Tyk Gateway API is capable of:  * Managing session objects (key generation) * Managing and listing policies * Managing and listing API Definitions (only when not using the Dashboard) * Hot reloads / reloading a cluster configuration * OAuth client creation (only when not using the Dashboard)   In order to use the Gateway API, you'll need to set the `secret` parameter in your tyk.conf file.  The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:  ``` x-tyk-authorization: <your-secret> ``` <br/> <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>

API version: 3.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// APIAllCertificateBasics APIAllCertificates represents a list of certificate basics
type APIAllCertificateBasics struct {
	Certs []CertificateBasics `json:"certs,omitempty"`
}

// NewAPIAllCertificateBasics instantiates a new APIAllCertificateBasics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPIAllCertificateBasics() *APIAllCertificateBasics {
	this := APIAllCertificateBasics{}
	return &this
}

// NewAPIAllCertificateBasicsWithDefaults instantiates a new APIAllCertificateBasics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPIAllCertificateBasicsWithDefaults() *APIAllCertificateBasics {
	this := APIAllCertificateBasics{}
	return &this
}

// GetCerts returns the Certs field value if set, zero value otherwise.
func (o *APIAllCertificateBasics) GetCerts() []CertificateBasics {
	if o == nil || o.Certs == nil {
		var ret []CertificateBasics
		return ret
	}
	return o.Certs
}

// GetCertsOk returns a tuple with the Certs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIAllCertificateBasics) GetCertsOk() ([]CertificateBasics, bool) {
	if o == nil || o.Certs == nil {
		return nil, false
	}
	return o.Certs, true
}

// HasCerts returns a boolean if a field has been set.
func (o *APIAllCertificateBasics) HasCerts() bool {
	if o != nil && o.Certs != nil {
		return true
	}

	return false
}

// SetCerts gets a reference to the given []CertificateBasics and assigns it to the Certs field.
func (o *APIAllCertificateBasics) SetCerts(v []CertificateBasics) {
	o.Certs = v
}

func (o APIAllCertificateBasics) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Certs != nil {
		toSerialize["certs"] = o.Certs
	}
	return json.Marshal(toSerialize)
}

type NullableAPIAllCertificateBasics struct {
	value *APIAllCertificateBasics
	isSet bool
}

func (v NullableAPIAllCertificateBasics) Get() *APIAllCertificateBasics {
	return v.value
}

func (v *NullableAPIAllCertificateBasics) Set(val *APIAllCertificateBasics) {
	v.value = val
	v.isSet = true
}

func (v NullableAPIAllCertificateBasics) IsSet() bool {
	return v.isSet
}

func (v *NullableAPIAllCertificateBasics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPIAllCertificateBasics(val *APIAllCertificateBasics) *NullableAPIAllCertificateBasics {
	return &NullableAPIAllCertificateBasics{value: val, isSet: true}
}

func (v NullableAPIAllCertificateBasics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPIAllCertificateBasics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


