/*
Tyk Gateway API

The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.  **Warning: Under no circumstances should outside parties be granted access to this API.**  The Tyk Gateway API is capable of:  * Managing session objects (key generation) * Managing and listing policies * Managing and listing API Definitions (only when not using the Dashboard) * Hot reloads / reloading a cluster configuration * OAuth client creation (only when not using the Dashboard)   In order to use the Gateway API, you'll need to set the `secret` parameter in your tyk.conf file.  The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:  ``` x-tyk-authorization: <your-secret> ``` <br/> <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>

API version: 3.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// APIDefinitionUptimeTestsConfig struct for APIDefinitionUptimeTestsConfig
type APIDefinitionUptimeTestsConfig struct {
	ExpireUtimeAfter *int64 `json:"expire_utime_after,omitempty"`
	RecheckWait *int64 `json:"recheck_wait,omitempty"`
	ServiceDiscovery *ServiceDiscoveryConfiguration `json:"service_discovery,omitempty"`
}

// NewAPIDefinitionUptimeTestsConfig instantiates a new APIDefinitionUptimeTestsConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPIDefinitionUptimeTestsConfig() *APIDefinitionUptimeTestsConfig {
	this := APIDefinitionUptimeTestsConfig{}
	return &this
}

// NewAPIDefinitionUptimeTestsConfigWithDefaults instantiates a new APIDefinitionUptimeTestsConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPIDefinitionUptimeTestsConfigWithDefaults() *APIDefinitionUptimeTestsConfig {
	this := APIDefinitionUptimeTestsConfig{}
	return &this
}

// GetExpireUtimeAfter returns the ExpireUtimeAfter field value if set, zero value otherwise.
func (o *APIDefinitionUptimeTestsConfig) GetExpireUtimeAfter() int64 {
	if o == nil || o.ExpireUtimeAfter == nil {
		var ret int64
		return ret
	}
	return *o.ExpireUtimeAfter
}

// GetExpireUtimeAfterOk returns a tuple with the ExpireUtimeAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionUptimeTestsConfig) GetExpireUtimeAfterOk() (*int64, bool) {
	if o == nil || o.ExpireUtimeAfter == nil {
		return nil, false
	}
	return o.ExpireUtimeAfter, true
}

// HasExpireUtimeAfter returns a boolean if a field has been set.
func (o *APIDefinitionUptimeTestsConfig) HasExpireUtimeAfter() bool {
	if o != nil && o.ExpireUtimeAfter != nil {
		return true
	}

	return false
}

// SetExpireUtimeAfter gets a reference to the given int64 and assigns it to the ExpireUtimeAfter field.
func (o *APIDefinitionUptimeTestsConfig) SetExpireUtimeAfter(v int64) {
	o.ExpireUtimeAfter = &v
}

// GetRecheckWait returns the RecheckWait field value if set, zero value otherwise.
func (o *APIDefinitionUptimeTestsConfig) GetRecheckWait() int64 {
	if o == nil || o.RecheckWait == nil {
		var ret int64
		return ret
	}
	return *o.RecheckWait
}

// GetRecheckWaitOk returns a tuple with the RecheckWait field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionUptimeTestsConfig) GetRecheckWaitOk() (*int64, bool) {
	if o == nil || o.RecheckWait == nil {
		return nil, false
	}
	return o.RecheckWait, true
}

// HasRecheckWait returns a boolean if a field has been set.
func (o *APIDefinitionUptimeTestsConfig) HasRecheckWait() bool {
	if o != nil && o.RecheckWait != nil {
		return true
	}

	return false
}

// SetRecheckWait gets a reference to the given int64 and assigns it to the RecheckWait field.
func (o *APIDefinitionUptimeTestsConfig) SetRecheckWait(v int64) {
	o.RecheckWait = &v
}

// GetServiceDiscovery returns the ServiceDiscovery field value if set, zero value otherwise.
func (o *APIDefinitionUptimeTestsConfig) GetServiceDiscovery() ServiceDiscoveryConfiguration {
	if o == nil || o.ServiceDiscovery == nil {
		var ret ServiceDiscoveryConfiguration
		return ret
	}
	return *o.ServiceDiscovery
}

// GetServiceDiscoveryOk returns a tuple with the ServiceDiscovery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionUptimeTestsConfig) GetServiceDiscoveryOk() (*ServiceDiscoveryConfiguration, bool) {
	if o == nil || o.ServiceDiscovery == nil {
		return nil, false
	}
	return o.ServiceDiscovery, true
}

// HasServiceDiscovery returns a boolean if a field has been set.
func (o *APIDefinitionUptimeTestsConfig) HasServiceDiscovery() bool {
	if o != nil && o.ServiceDiscovery != nil {
		return true
	}

	return false
}

// SetServiceDiscovery gets a reference to the given ServiceDiscoveryConfiguration and assigns it to the ServiceDiscovery field.
func (o *APIDefinitionUptimeTestsConfig) SetServiceDiscovery(v ServiceDiscoveryConfiguration) {
	o.ServiceDiscovery = &v
}

func (o APIDefinitionUptimeTestsConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ExpireUtimeAfter != nil {
		toSerialize["expire_utime_after"] = o.ExpireUtimeAfter
	}
	if o.RecheckWait != nil {
		toSerialize["recheck_wait"] = o.RecheckWait
	}
	if o.ServiceDiscovery != nil {
		toSerialize["service_discovery"] = o.ServiceDiscovery
	}
	return json.Marshal(toSerialize)
}

type NullableAPIDefinitionUptimeTestsConfig struct {
	value *APIDefinitionUptimeTestsConfig
	isSet bool
}

func (v NullableAPIDefinitionUptimeTestsConfig) Get() *APIDefinitionUptimeTestsConfig {
	return v.value
}

func (v *NullableAPIDefinitionUptimeTestsConfig) Set(val *APIDefinitionUptimeTestsConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableAPIDefinitionUptimeTestsConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableAPIDefinitionUptimeTestsConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPIDefinitionUptimeTestsConfig(val *APIDefinitionUptimeTestsConfig) *NullableAPIDefinitionUptimeTestsConfig {
	return &NullableAPIDefinitionUptimeTestsConfig{value: val, isSet: true}
}

func (v NullableAPIDefinitionUptimeTestsConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPIDefinitionUptimeTestsConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


