/*
Tyk Gateway API

The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.  **Warning: Under no circumstances should outside parties be granted access to this API.**  The Tyk Gateway API is capable of:  * Managing session objects (key generation) * Managing and listing policies * Managing and listing API Definitions (only when not using the Dashboard) * Hot reloads / reloading a cluster configuration * OAuth client creation (only when not using the Dashboard)   In order to use the Gateway API, you'll need to set the `secret` parameter in your tyk.conf file.  The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:  ``` x-tyk-authorization: <your-secret> ``` <br/> <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>

API version: 3.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// APIDefinitionOauthMeta struct for APIDefinitionOauthMeta
type APIDefinitionOauthMeta struct {
	AllowedAccessTypes []string `json:"allowed_access_types,omitempty"`
	AllowedAuthorizeTypes []string `json:"allowed_authorize_types,omitempty"`
	AuthLoginRedirect *string `json:"auth_login_redirect,omitempty"`
}

// NewAPIDefinitionOauthMeta instantiates a new APIDefinitionOauthMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPIDefinitionOauthMeta() *APIDefinitionOauthMeta {
	this := APIDefinitionOauthMeta{}
	return &this
}

// NewAPIDefinitionOauthMetaWithDefaults instantiates a new APIDefinitionOauthMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPIDefinitionOauthMetaWithDefaults() *APIDefinitionOauthMeta {
	this := APIDefinitionOauthMeta{}
	return &this
}

// GetAllowedAccessTypes returns the AllowedAccessTypes field value if set, zero value otherwise.
func (o *APIDefinitionOauthMeta) GetAllowedAccessTypes() []string {
	if o == nil || o.AllowedAccessTypes == nil {
		var ret []string
		return ret
	}
	return o.AllowedAccessTypes
}

// GetAllowedAccessTypesOk returns a tuple with the AllowedAccessTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionOauthMeta) GetAllowedAccessTypesOk() ([]string, bool) {
	if o == nil || o.AllowedAccessTypes == nil {
		return nil, false
	}
	return o.AllowedAccessTypes, true
}

// HasAllowedAccessTypes returns a boolean if a field has been set.
func (o *APIDefinitionOauthMeta) HasAllowedAccessTypes() bool {
	if o != nil && o.AllowedAccessTypes != nil {
		return true
	}

	return false
}

// SetAllowedAccessTypes gets a reference to the given []string and assigns it to the AllowedAccessTypes field.
func (o *APIDefinitionOauthMeta) SetAllowedAccessTypes(v []string) {
	o.AllowedAccessTypes = v
}

// GetAllowedAuthorizeTypes returns the AllowedAuthorizeTypes field value if set, zero value otherwise.
func (o *APIDefinitionOauthMeta) GetAllowedAuthorizeTypes() []string {
	if o == nil || o.AllowedAuthorizeTypes == nil {
		var ret []string
		return ret
	}
	return o.AllowedAuthorizeTypes
}

// GetAllowedAuthorizeTypesOk returns a tuple with the AllowedAuthorizeTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionOauthMeta) GetAllowedAuthorizeTypesOk() ([]string, bool) {
	if o == nil || o.AllowedAuthorizeTypes == nil {
		return nil, false
	}
	return o.AllowedAuthorizeTypes, true
}

// HasAllowedAuthorizeTypes returns a boolean if a field has been set.
func (o *APIDefinitionOauthMeta) HasAllowedAuthorizeTypes() bool {
	if o != nil && o.AllowedAuthorizeTypes != nil {
		return true
	}

	return false
}

// SetAllowedAuthorizeTypes gets a reference to the given []string and assigns it to the AllowedAuthorizeTypes field.
func (o *APIDefinitionOauthMeta) SetAllowedAuthorizeTypes(v []string) {
	o.AllowedAuthorizeTypes = v
}

// GetAuthLoginRedirect returns the AuthLoginRedirect field value if set, zero value otherwise.
func (o *APIDefinitionOauthMeta) GetAuthLoginRedirect() string {
	if o == nil || o.AuthLoginRedirect == nil {
		var ret string
		return ret
	}
	return *o.AuthLoginRedirect
}

// GetAuthLoginRedirectOk returns a tuple with the AuthLoginRedirect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIDefinitionOauthMeta) GetAuthLoginRedirectOk() (*string, bool) {
	if o == nil || o.AuthLoginRedirect == nil {
		return nil, false
	}
	return o.AuthLoginRedirect, true
}

// HasAuthLoginRedirect returns a boolean if a field has been set.
func (o *APIDefinitionOauthMeta) HasAuthLoginRedirect() bool {
	if o != nil && o.AuthLoginRedirect != nil {
		return true
	}

	return false
}

// SetAuthLoginRedirect gets a reference to the given string and assigns it to the AuthLoginRedirect field.
func (o *APIDefinitionOauthMeta) SetAuthLoginRedirect(v string) {
	o.AuthLoginRedirect = &v
}

func (o APIDefinitionOauthMeta) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AllowedAccessTypes != nil {
		toSerialize["allowed_access_types"] = o.AllowedAccessTypes
	}
	if o.AllowedAuthorizeTypes != nil {
		toSerialize["allowed_authorize_types"] = o.AllowedAuthorizeTypes
	}
	if o.AuthLoginRedirect != nil {
		toSerialize["auth_login_redirect"] = o.AuthLoginRedirect
	}
	return json.Marshal(toSerialize)
}

type NullableAPIDefinitionOauthMeta struct {
	value *APIDefinitionOauthMeta
	isSet bool
}

func (v NullableAPIDefinitionOauthMeta) Get() *APIDefinitionOauthMeta {
	return v.value
}

func (v *NullableAPIDefinitionOauthMeta) Set(val *APIDefinitionOauthMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableAPIDefinitionOauthMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableAPIDefinitionOauthMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPIDefinitionOauthMeta(val *APIDefinitionOauthMeta) *NullableAPIDefinitionOauthMeta {
	return &NullableAPIDefinitionOauthMeta{value: val, isSet: true}
}

func (v NullableAPIDefinitionOauthMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPIDefinitionOauthMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


