/*
Tyk Gateway API

The Tyk Gateway API is the primary means for integrating your application with the Tyk API Gateway system. This API is very small, and has no granular permissions system. It is intended to be used purely for internal automation and integration.  **Warning: Under no circumstances should outside parties be granted access to this API.**  The Tyk Gateway API is capable of:  * Managing session objects (key generation) * Managing and listing policies * Managing and listing API Definitions (only when not using the Dashboard) * Hot reloads / reloading a cluster configuration * OAuth client creation (only when not using the Dashboard)   In order to use the Gateway API, you'll need to set the `secret` parameter in your tyk.conf file.  The shared secret you set should then be sent along as a header with each Gateway API Request in order for it to be successful:  ``` x-tyk-authorization: <your-secret> ``` <br/> <b>The Tyk Gateway API is subsumed by the Tyk Dashboard API in Pro installations.</b>

API version: 3.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// EndPointMeta struct for EndPointMeta
type EndPointMeta struct {
	MethodActions *map[string]EndpointMethodMeta `json:"method_actions,omitempty"`
	Path *string `json:"path,omitempty"`
}

// NewEndPointMeta instantiates a new EndPointMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndPointMeta() *EndPointMeta {
	this := EndPointMeta{}
	return &this
}

// NewEndPointMetaWithDefaults instantiates a new EndPointMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndPointMetaWithDefaults() *EndPointMeta {
	this := EndPointMeta{}
	return &this
}

// GetMethodActions returns the MethodActions field value if set, zero value otherwise.
func (o *EndPointMeta) GetMethodActions() map[string]EndpointMethodMeta {
	if o == nil || o.MethodActions == nil {
		var ret map[string]EndpointMethodMeta
		return ret
	}
	return *o.MethodActions
}

// GetMethodActionsOk returns a tuple with the MethodActions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndPointMeta) GetMethodActionsOk() (*map[string]EndpointMethodMeta, bool) {
	if o == nil || o.MethodActions == nil {
		return nil, false
	}
	return o.MethodActions, true
}

// HasMethodActions returns a boolean if a field has been set.
func (o *EndPointMeta) HasMethodActions() bool {
	if o != nil && o.MethodActions != nil {
		return true
	}

	return false
}

// SetMethodActions gets a reference to the given map[string]EndpointMethodMeta and assigns it to the MethodActions field.
func (o *EndPointMeta) SetMethodActions(v map[string]EndpointMethodMeta) {
	o.MethodActions = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *EndPointMeta) GetPath() string {
	if o == nil || o.Path == nil {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndPointMeta) GetPathOk() (*string, bool) {
	if o == nil || o.Path == nil {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *EndPointMeta) HasPath() bool {
	if o != nil && o.Path != nil {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *EndPointMeta) SetPath(v string) {
	o.Path = &v
}

func (o EndPointMeta) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.MethodActions != nil {
		toSerialize["method_actions"] = o.MethodActions
	}
	if o.Path != nil {
		toSerialize["path"] = o.Path
	}
	return json.Marshal(toSerialize)
}

type NullableEndPointMeta struct {
	value *EndPointMeta
	isSet bool
}

func (v NullableEndPointMeta) Get() *EndPointMeta {
	return v.value
}

func (v *NullableEndPointMeta) Set(val *EndPointMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableEndPointMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableEndPointMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndPointMeta(val *EndPointMeta) *NullableEndPointMeta {
	return &NullableEndPointMeta{value: val, isSet: true}
}

func (v NullableEndPointMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndPointMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


